# Generated by Django 3.2.25 on 2025-11-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recepie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipe',
        ),
    ]
